default_context:
  project_type: "app"
  project_name: "TODO"
  project_description: "TODO"
  project_url: "https://github.com/to/do"
  author_name: "TODO"
  author_email: "to@do.com"
  python_version: "3.10"
  docker_image: "python:3.10-slim"
  development_environment: "simple"
  with_conventional_commits: "0"
  with_fastapi_api: "1"
  with_typer_cli: "1"
  continuous_integration: "GitHub"
  private_package_repository_name: ""
  private_package_repository_url: ""
